#!/bin/bash
#
# Copyright 2016-2022 Matt Evans
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

FPATH=$1

COUNTER_NAMES=`egrep -r --include "*.cc" --include "*.h" "COUNT\( *CTR_.*\)" ${FPATH} | sed -e "s/^.*COUNT *(//; s/).*$//;" | sort | uniq`


echo "enum { COUNTER_START = 0,"
echo $COUNTER_NAMES | sed -e "s/ /, /g;"
echo ", COUNTER_MAX };"

echo "static __attribute__((unused)) const char *global_counter_names[] = {"
echo -n \"
echo $COUNTER_NAMES | sed -e "s/ /\", \"/g; s/$/\",/;"
echo "};"

